### ISSUE TITLE
Create and update Edge Deployment entries in the ConfigDB

### ISSUE THREAD

**Issue by amrc-benmorrow** [AMRC-FactoryPlus/acs-manager#51]
Instead of deploying to k8s directly, the manager needs to create ConfigDB entries.

Some of this work has already been started, but the schema for the edge deployment entries has changed.

**Comment by amrc-benmorrow** [comment]
https://github.com/AMRC-FactoryPlus/acs-edge-sync/issues/6

**Comment by AlexGodbehere** [comment]
TODO:

- [ ] Set up dev environment pointing to v3 dev cluster
- [ ] Replace node provisioning with configDB entry
- [ ] Remove EA management page
