### ISSUE TITLE
Manager does not recover from GSSAPI errors

### ISSUE THREAD

**Issue by amrc-benmorrow** [AMRC-FactoryPlus/acs-manager#74]
There is a persistent issue with the Manager that only shows up when the pod has been running for a while. When the Manager tries to fetch a token for a F+ service, the GSS `acquireCredentials` call in ServiceClient.php is throwing an exception with GSSAPI minor code 39756033, which is apparently 'No key table entry found'. Restarting the manager stops this from happening.

* The error message may indicate the `acquireCredentials` call is trying to get server creds rather than client creds?
* The fact this only appears after several hours suggests this is a ticket expiration problem. However I cannot see from the code how we could be trying to use an expired ticket. The KDC logs confirm that the KDC is issuing a fresh TGT to sv1manager each time.

**Comment by amrc-benmorrow** [comment]
This was a red herring. The Manager was attempting to contact the EDO / Clusters operator at the fixed hostname prefix `clusters`, which didn't match the deployment yet.

The manager does not appear to recover very well from GSSAPI errors (ticket title changed). A GSSAPI exeception does not cause a manager crash, but does leave the Manager in a state where a restart is required to recover.

**Comment by AlexGodbehere** [comment]
@amrc-benmorrow will the new user-privilege based approach likely fix this?

**Comment by amrc-benmorrow** [comment]
It's possible, especially if the code is being more careful to catch and recover from GSSAPI exceptions.

**Comment by amrc-benmorrow** [comment]
It's not clear this is still an issue. A new ticket can be opened if necessary.
